steps:
  - command: 
    - echo 'Deploy'
    - echo %BUILDKITE_BUILD_NUMBER%
    - echo %RELEASE_VERSION%
    label: ":rocket:"
    concurrency_group: "$BUILDKITE_PIPELINE_SLUG-deploy"
    concurrency: 1
    branches: "main"
