steps:
  - command:
    - echo 'Tests'
    - buildkite-agent meta-data set "release-version" "1.1"
    label: ':hammer:'
  - wait
  - trigger: dummy-deploy
    label: ":rocket:"
    branches: "main"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
