steps:
  - command: echo 'Tests'
    label: ':hammer:'
  - wait
  - trigger: pipeline-deploy
    label: ":rocket:"
    branches: "master"
    async: true
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
