steps:
  - command: echo 'Tests'
    label: ':hammer:'
  - wait
  - trigger: dummy-deploy
    label: ":rocket:"
    branches: "main"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
      release-version: "1.1"
