steps:
  - command: echo 'Tests'
    label: ':hammer:'
  - wait
  - trigger: dummy-deploy
    # parallelism: 2
    label: ":rocket:"
    branches: "main"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      env:
        FLATBUILD_NAME: "8295_FlatBuild_49-20241115.tgz"
