steps:
  - command: 
    - echo 'Deploy'
    - echo " release-version = $(buildkite-agent meta-data get 'release-version')"
    label: ":rocket:"
    concurrency_group: "$BUILDKITE_PIPELINE_SLUG-deploy"
    concurrency: 1
    branches: "main"
